// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Y1ZyHdSPHbgJG6dOPCLzrVAncCAOPpU',
    appId: '1:144753848625:web:61591f3c0fa444e6224010',
    messagingSenderId: '144753848625',
    projectId: 'ink-ai-8e980',
    authDomain: 'ink-ai-8e980.firebaseapp.com',
    storageBucket: 'ink-ai-8e980.firebasestorage.app',
    measurementId: 'G-5JLJ17J5FY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlNeGTPar8Yo9payefaCaQxCndkw33KJs',
    appId: '1:144753848625:android:d2379db3e8206cd8224010',
    messagingSenderId: '144753848625',
    projectId: 'ink-ai-8e980',
    storageBucket: 'ink-ai-8e980.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaZUpzN5HVBiNE-Gf-3PmVZszfu3bdWs8',
    appId: '1:144753848625:ios:78b91e49e91aeded224010',
    messagingSenderId: '144753848625',
    projectId: 'ink-ai-8e980',
    storageBucket: 'ink-ai-8e980.firebasestorage.app',
    iosBundleId: 'com.inkai.inkAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaZUpzN5HVBiNE-Gf-3PmVZszfu3bdWs8',
    appId: '1:144753848625:ios:78b91e49e91aeded224010',
    messagingSenderId: '144753848625',
    projectId: 'ink-ai-8e980',
    storageBucket: 'ink-ai-8e980.firebasestorage.app',
    iosBundleId: 'com.inkai.inkAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0Y1ZyHdSPHbgJG6dOPCLzrVAncCAOPpU',
    appId: '1:144753848625:web:fb4166b372aaf697224010',
    messagingSenderId: '144753848625',
    projectId: 'ink-ai-8e980',
    authDomain: 'ink-ai-8e980.firebaseapp.com',
    storageBucket: 'ink-ai-8e980.firebasestorage.app',
    measurementId: 'G-K0M3LY4WQX',
  );
}
